<?php

declare(strict_types=1);

namespace nuelcyoung\tenantable\Config;

class Tenantable extends \CodeIgniter\Config\BaseConfig
{
    public string $packageName = 'tenantable';

    public string $baseDomain = 'localhost';

    public string $tenantsTable   = 'tenants';
    public string $tenantIdColumn = 'tenant_id';

    public bool   $separateDatabasePerTenant = false;
    public string $defaultDatabaseGroup      = 'default';

    /**
     * Callable that derives the tenant database name from the tenant row.
     *
     * Signature: function(array $tenant): string
     *
     * When null the package uses the built-in default: "tenant_{id}".
     * Set this to a Closure, invokable class, or any PHP callable to
     * implement a custom naming convention (e.g. based on subdomain).
     *
     * @var callable|null
     */
    public $databaseNameGenerator = null;

    /**
     * Tenant isolation strategy. One of:
     *   - 'row'      Shared DB, tenant_id column on tenant-scoped tables.
     *   - 'prefix'   Shared DB, per-tenant table prefixes (tenant_{id}_*).
     *   - 'database' Database-per-tenant.
     *
     * Read by the tenants:setup command. When null, the command derives it
     * from $separateDatabasePerTenant (database if true, else row).
     */
    public ?string $isolationMode = null;

    /**
     * Automatically CREATE DATABASE when a new tenant is inserted.
     *
     * Only applies when isolation mode is 'database'. The DB user
     * configured in Config\Database must have CREATE privileges.
     */
    public bool $autoCreateDatabase = true;

    /**
     * Automatically run tenant migrations after creating the database.
     *
     * Only applies when $autoCreateDatabase is true and isolation mode
     * is 'database'. Uses $tenantMigrationsNamespace for the migrations.
     */
    public bool $autoMigrateTenant = true;

    /**
     * PSR-4 namespace holding the consuming app's per-tenant migrations.
     * Required for 'prefix' and 'database' isolation modes.
     * Example: 'App\Database\Migrations\Tenant'
     */
    public ?string $tenantMigrationsNamespace = 'App\Database\Migrations\Tenant';

    /**
     * Additional PSR-4 namespaces whose migrations should also run on
     * each tenant database.  Use this to include third-party package
     * migrations (e.g. Shield) without copying their migration files.
     *
     * Example:
     *   public array $tenantMigrationsNamespaces = [
     *       'CodeIgniter\Shield\Database\Migrations',
     *   ];
     *
     * The primary $tenantMigrationsNamespace is always included
     * automatically — you do NOT need to list it here.
     */
    public array $tenantMigrationsNamespaces = [];

    /**
     * Default namespace for tenant-scoped models generated by `tenants:make-model`.
     * Override per-call with the `--namespace=` flag.
     */
    public string $tenantModelsNamespace = 'App\Models\Tenant';

    /**
     * Default namespace for global (non-tenant) models generated by
     * `tenants:make-model --global`. Override per-call with `--namespace=`.
     */
    public string $globalModelsNamespace = 'App\Models';

    /**
     * How the package identifies which tenant a request belongs to.
     *
     * This value determines which filter class the 'tenant' alias resolves
     * to when you register filters via registerFilters(). Apply the chosen
     * filter to your routes in app/Config/Filters.php.
     *
     * Supported values and their filter classes:
     *
     *   'tenant_subdomain'           → SubdomainFilter
     *       Identifies by subdomain: acme.example.com → tenant "acme"
     *
     *   'tenant_domain'              → DomainFilter
     *       Identifies by custom domain stored in tenant_domains table
     *
     *   'tenant_domain_or_subdomain' → DomainOrSubdomainFilter
     *       Tries domain first, falls back to subdomain
     *
     *   'tenant_path'                → PathFilter
     *       Identifies by first URL path segment: /acme/dashboard → tenant "acme"
     *
     *   'tenant_request'             → RequestDataFilter
     *       Identifies from request header, query param, or body field
     *
     * Usage in app/Config/Filters.php:
     *
     *   public array $globals = [
     *       'before' => [
     *           'tenant_subdomain' => ['except' => ['health', 'api/*']],
     *       ],
     *   ];
     *
     * You can also use different strategies on different route groups:
     *
     *   $routes->group('app', ['filter' => 'tenant_subdomain'], ...);
     *   $routes->group('api', ['filter' => 'tenant_request'], ...);
     */
    public string $identificationMethod = 'tenant_subdomain';

    /**
     * Default resolution strategy for IdentifyTenant filter.
     * One of: 'domain', 'subdomain', 'domain_or_subdomain', 'request_data', 'path'
     */
    public string $defaultStrategy = 'domain_or_subdomain';

    public array $superadminGroups = ['superadmin'];

    public bool $tenantFilteringEnabled = true;

    public array $bypassRoutes = [
        'api/*',
        'health',
        '_health',
    ];

    public bool    $throwExceptions = false;
    public ?string $notFoundView    = null;
    public ?string $inactiveView    = null;

    public ?int $fallbackTenantId = null;
    public bool $allowLocalhost   = true;

    /**
     * Development tenant ID to auto-activate when request comes from localhost.
     * When null, localhost requests proceed without tenant context (no 404).
     */
    public ?int $developmentTenantId = null;

    public bool $cacheTenantData = true;
    public int  $cacheTtl        = 3600;

    /**
     * Cache TTL for domain-to-tenant resolver (seconds).
     */
    public int $resolverCacheTtl = 300;

    /**
     * Cache key prefix for resolver cache.
     */
    public string $resolverCachePrefix = 'tenant_resolver';

    /**
     * Early detection strategy for pre_system bootstrap.
     * One of: 'subdomain', 'domain', 'domain_or_subdomain', 'off'
     */
    public string $earlyDetectionStrategy = 'domain_or_subdomain';

    /**
     * Trusted host patterns for HTTP_HOST validation.
     * Supports wildcards: ['*.app.test', 'app.test']
     * Set to null to disable validation (not recommended).
     */
    public ?array $trustedHostPatterns = null;

    public array $bootstrappers = [
        'database' => \nuelcyoung\tenantable\Bootstrap\Systems\DatabaseSystem::class,
        'table'    => \nuelcyoung\tenantable\Bootstrap\Systems\TableSystem::class,
        'cache'    => \nuelcyoung\tenantable\Bootstrap\Systems\CacheSystem::class,
        'storage'  => \nuelcyoung\tenantable\Bootstrap\Systems\StorageSystem::class,
        'session'  => \nuelcyoung\tenantable\Bootstrap\Systems\SessionSystem::class,
        'logging'  => \nuelcyoung\tenantable\Bootstrap\Systems\LoggingSystem::class,
        'config'   => \nuelcyoung\tenantable\Bootstrap\Systems\ConfigSystem::class,
    ];

    public array $subdomainRules = [
        'min_length' => 2,
        'max_length' => 50,
        'pattern'    => '/^[a-z0-9][a-z0-9-]*[a-z0-9]$/',
    ];

    public function registerFilters(): array
    {
        return [
            'tenant'                     => \nuelcyoung\tenantable\Filters\TenantFilter::class,
            'tenant_subdomain'           => \nuelcyoung\tenantable\Filters\SubdomainFilter::class,
            'tenant_domain'              => \nuelcyoung\tenantable\Filters\DomainFilter::class,
            'tenant_domain_or_subdomain' => \nuelcyoung\tenantable\Filters\DomainOrSubdomainFilter::class,
            'tenant_path'                => \nuelcyoung\tenantable\Filters\PathFilter::class,
            'tenant_request'             => \nuelcyoung\tenantable\Filters\RequestDataFilter::class,
            'identify_tenant'            => \nuelcyoung\tenantable\Filters\IdentifyTenant::class,
        ];
    }

    /** @deprecated Use registerFilters() instead */
    public function registerFilter(): array
    {
        return ['tenant' => \nuelcyoung\tenantable\Filters\TenantFilter::class];
    }
}
